/**
 * The FAAM Stock Paper — public feed for faam-official.netlify.app.
 *
 * The FAAM app is where stories are written. Whenever the FAAM (dev) account
 * publishes or deletes one, the app pushes the current set of stories here, so
 * they appear on the website without a redeploy. Readers only ever GET.
 *
 * Routed by netlify.toml:  /api/paper  and  /api/paper/*  ->  this function
 *
 *   GET  /api/paper              all stories, pinned first then newest
 *   GET  /api/paper?latest=1     just the newest story (for the landing page)
 *   GET  /api/paper/img/<id>     an AI illustration
 *   POST /api/paper/sync         replace the story list        (token required)
 *   PUT  /api/paper/img/<id>     upload one illustration        (token required)
 *
 * Writes need  Authorization: Bearer <FAAM_PAPER_TOKEN>  — set that environment
 * variable in Netlify to the same value the FAAM app has in ~/.faam/paper_site_token.
 */
import { getStore } from "@netlify/blobs";
import crypto from "node:crypto";

const MAX_POSTS = 300;
const MAX_TITLE = 140;
const MAX_BODY = 8000;
const MAX_IMAGE_BYTES = 3 * 1024 * 1024;
const MAX_SYNC_BYTES = 4 * 1024 * 1024;
const KINDS = new Set(["Market", "Earnings", "Explainer", "Announcement"]);
const POST_ID = /^[0-9a-f]{6,24}$/;
const IMAGE_ID = /^[0-9a-f]{16}$/;
const TICKER = /^[A-Z0-9.\-^=]{1,12}$/;

const store = () => getStore("faam-paper");
const STRONG = { consistency: "strong" };   // a freshly published story must show at once

function json(body, status = 200, extra = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", ...extra },
  });
}

/* Only the FAAM app holds the token. Constant-time compare so it can't be
   guessed a character at a time. No token configured = no writes at all. */
function authorised(req) {
  const want = (process.env.FAAM_PAPER_TOKEN || "").trim();
  if (want.length < 24) return false;
  const got = (req.headers.get("authorization") || "").replace(/^Bearer\s+/i, "").trim();
  const a = Buffer.from(got), b = Buffer.from(want);
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}

const str = (v, max) => (typeof v === "string" ? v : "").slice(0, max);

/* Keep exactly the public fields, re-validated here — the site never trusts
   that the sender got it right. */
function clean(p) {
  if (!p || typeof p !== "object" || !POST_ID.test(p.id || "")) return null;
  const title = str(p.title, MAX_TITLE).trim();
  const body = str(p.body, MAX_BODY).trim();
  if (!title || !body) return null;
  const image = IMAGE_ID.test(p.image || "") ? p.image : "";
  return {
    id: p.id,
    title,
    body,
    kind: KINDS.has(p.kind) ? p.kind : "Market",
    tickers: (Array.isArray(p.tickers) ? p.tickers : [])
      .map((t) => String(t).toUpperCase()).filter((t) => TICKER.test(t)).slice(0, 6),
    ts: Number.isFinite(+p.ts) ? Math.max(0, Math.floor(+p.ts)) : 0,
    pinned: !!p.pinned,
    developing: !!p.developing,
    image,
    imageCaption: image ? str(p.imageCaption, 80) || "Illustration generated by AI" : "",
    comments: Number.isFinite(+p.comments) ? Math.max(0, Math.floor(+p.comments)) : 0,
  };
}

async function readPosts() {
  return (await store().get("posts", { type: "json", ...STRONG })) || [];
}

function ordered(posts) {
  return posts.slice().sort((a, b) => (b.pinned - a.pinned) || (b.ts - a.ts));
}

async function listImages() {
  const res = await store().list({ prefix: "img-" });
  return new Set((res.blobs || []).map((b) => b.key.slice(4)));
}

async function sync(req) {
  const len = Number(req.headers.get("content-length") || 0);
  if (len > MAX_SYNC_BYTES) return json({ error: "payload too large" }, 413);
  let data;
  try { data = await req.json(); } catch { return json({ error: "invalid JSON" }, 400); }
  if (!Array.isArray(data.posts)) return json({ error: "posts must be a list" }, 400);

  const seen = new Set();
  const posts = [];
  for (const raw of data.posts.slice(0, MAX_POSTS)) {
    const p = clean(raw);
    if (p && !seen.has(p.id)) { seen.add(p.id); posts.push(p); }
  }
  await store().setJSON("posts", posts);

  // Ask for any picture we don't have yet, and drop pictures no story uses.
  const have = await listImages();
  const wanted = new Set(posts.map((p) => p.image).filter(Boolean));
  for (const id of have) if (!wanted.has(id)) await store().delete(`img-${id}`);
  const missingImages = [...wanted].filter((id) => !have.has(id));
  return json({ ok: true, count: posts.length, missingImages });
}

async function putImage(req, id) {
  if (!IMAGE_ID.test(id)) return json({ error: "bad image id" }, 400);
  const buf = new Uint8Array(await req.arrayBuffer());
  if (!buf.length || buf.length > MAX_IMAGE_BYTES) return json({ error: "image too large or empty" }, 413);
  // JPEG only: these are the illustrations FAAM generates.
  if (!(buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff)) return json({ error: "not a JPEG" }, 415);
  await store().set(`img-${id}`, buf);
  return json({ ok: true });
}

async function getImage(id) {
  if (!IMAGE_ID.test(id)) return json({ error: "not found" }, 404);
  const data = await store().get(`img-${id}`, { type: "arrayBuffer" });
  if (!data) return json({ error: "not found" }, 404);
  return new Response(data, {
    headers: {
      "content-type": "image/jpeg",
      // An id never gets new contents, so browsers can keep it forever.
      "cache-control": "public, max-age=31536000, immutable",
    },
  });
}

export default async (req) => {
  const url = new URL(req.url);
  // Works whether the path arrives as /api/paper/... or /.netlify/functions/paper/...
  const rest = url.pathname.replace(/^.*?\/(?:api|functions)\/paper\/?/, "").replace(/\/+$/, "");
  try {
    if (req.method === "GET") {
      if (rest.startsWith("img/")) return await getImage(rest.slice(4));
      if (rest) return json({ error: "not found" }, 404);
      const posts = ordered(await readPosts());
      if (url.searchParams.get("latest")) {
        const newest = posts.slice().sort((a, b) => b.ts - a.ts)[0];
        return json({ posts: newest ? [newest] : [] });
      }
      return json({ posts });
    }

    if (!authorised(req)) return json({ error: "not allowed" }, 401);
    if (req.method === "POST" && rest === "sync") return await sync(req);
    if (req.method === "PUT" && rest.startsWith("img/")) return await putImage(req, rest.slice(4));
    return json({ error: "not found" }, 404);
  } catch (e) {
    return json({ error: "server error" }, 500);
  }
};
