/* Cases for site/paper/index.html. Run with tests/run.sh. */
var pass = 0, fail = 0;
function ok(c, m) { c ? pass++ : fail++; print((c ? "  PASS " : "  FAIL ") + m); }
FEED = [
  { id: "aaa111", title: "Chip stocks are having a big week", kind: "Market", tickers: ["AMD", "NVDA"], ts: 300,
    pinned: false, developing: true, image: "", imageCaption: "", comments: 3,
    body: "AMD shares rose.\n\nWhat we know so far: plenty." },
  { id: "bbb222", title: "What a P/E ratio tells you", kind: "Explainer", tickers: [], ts: 200,
    pinned: false, developing: false, image: "", imageCaption: "", comments: 0, body: "P/E compares price to earnings." },
  { id: "ccc333", title: "<img src=x onerror=alert(1)>", kind: "Announcement", tickers: [], ts: 100,
    pinned: false, developing: false, image: "0123456789abcdef", imageCaption: "Illustration generated by AI",
    comments: 1, body: "Welcome." },
];
async function run() {
  await settle(); await settle();
  var cards = REG.grid.children;
  ok(cards.length === 3, "front page shows all 3 stories");
  ok(cards[0].className === "card wide" && cards[1].className === "card", "first story is the wide lead");
  ok(cards[0].children[0].children[0].className === "dev", "DEVELOPING badge on a developing story");
  ok(cards[0].children[0].tagName === "p", "no picture element when a story has none");
  ok(cards[1].href === "#bbb222", "cards link to their story");
  ok(/3 comments/.test(cards[0].textContent) && !/comment/.test(cards[1].textContent), "comment counts");
  ok(cards[2].textContent.indexOf("<img") >= 0, "HTML in a title is shown as text, not run");
  ok(REG.empty.hidden && REG.err.hidden, "no empty/error message when stories exist");

  location.hash = "#aaa111"; fire("hashchange");
  ok(REG.front.hidden && !REG.storyView.hidden, "opening a story swaps the view");
  ok(REG.sTitle.textContent === "Chip stocks are having a big week", "story headline");
  ok(REG.sBody.children.length === 2, "body split into paragraphs on blank lines");
  ok(REG.sTicks.children.map(function (c) { return c.textContent; }).join() === "$AMD,$NVDA", "ticker chips");
  ok(REG.sFig.hidden, "no figure without a picture");
  ok(/discussing this in FAAM/.test(REG.sJoin.textContent), "points readers to the app for comments");
  ok(document.title.indexOf("Chip stocks") === 0, "tab title follows the story");

  location.hash = "#ccc333"; fire("hashchange");
  ok(!REG.sFig.hidden && REG.sImg.src === "/api/paper/img/0123456789abcdef", "picture shown with its URL");
  ok(REG.sCap.textContent === "Illustration generated by AI", "AI caption shown");

  location.hash = "#nope"; fire("hashchange");
  ok(!REG.front.hidden && REG.storyView.hidden, "unknown story falls back to the front page");

  FEED.push({ id: "ddd444", title: "Brand new story", kind: "Market", tickers: [], ts: 9e9,
              pinned: false, developing: false, image: "", imageCaption: "", comments: 0, body: "Fresh." });
  timers[0](); await settle(); await settle();
  ok(REG.grid.children.length === 4, "a newly published story appears on the next refresh, no reload");

  FAIL = true; timers[0](); await settle(); await settle();
  ok(REG.err.hidden && REG.grid.children.length === 4, "a failed refresh keeps the stories on screen");

  FEED = []; FAIL = false; timers[0](); await settle(); await settle();
  ok(!REG.empty.hidden && REG.grid.children.length === 0, "an empty paper says so");

  print("\n" + pass + " passed, " + fail + " failed");
}
